# --------------------
# Define non-modifiable values
# --------------------


# ==================== Alas ====================

Alas:
  Emulator:
    ControlMethod: MaaTouch
  Optimization:
    ScreenshotInterval: 0.2
    CombatScreenshotInterval: 1.0
Restart:
  Scheduler:
    ServerUpdate: 04:00

# ==================== Daily ====================

Dungeon:
  DungeonSupport:
    Use:
      option: [ when_daily, always_use ]
DailyQuest:
  Scheduler:
BattlePass:
  Scheduler:
Assignment:
  Scheduler:
DataUpdate:

# ==================== Weekly ====================

Weekly:
  DungeonSupport:
    Use:
      option: [ always_use, do_not_use ]
Ornament:
  DungeonSupport:
    Use:
      option: [ when_daily, always_use ]
